---
- name: Download telegraf archive compatibility key
  ansible.builtin.get_url:
    url: "{{ telegraf_key_url }}"
    dest: /tmp/telegraf-archive_compat.key
    mode: "0644"
  changed_when: false

- name: Dearmor and install telegraf key into trusted.gpg.d
  ansible.builtin.command: >
    gpg --batch --yes --dearmor
        --output "{{ apt_key_path }}/influxdb2.gpg"
        /tmp/telegraf-archive_compat.key
  args:
    creates: "{{ apt_key_path }}/influxdb2.gpg"
  changed_when: false

- name: Delete temporary telegraf key file
  ansible.builtin.file:
    name: /tmp/telegraf-archive_compat.key
    state: absent
  changed_when: false

- name: Add telegraf APT repository
  ansible.builtin.apt_repository:
    repo: "{{ telegraf_apt_repo }}"
    filename: influx
    state: present

- name: Install Telegraf package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ telegraf_package }}"
