---
- name: Download Telegraf GPG key
  ansible.builtin.get_url:
    url: "{{ telegraf_key_url }}"
    dest: /tmp/telegraf-rpm.key
    mode: "0644"
  changed_when: false

- name: Import Telegraf GPG key into RPM database
  ansible.builtin.command: >
    rpm --import /tmp/telegraf-rpm.key
  args:
    creates: /etc/pki/rpm-gpg/RPM-GPG-KEY-influxdata
  changed_when: false

- name: Remove temporary Telegraf key file
  ansible.builtin.file:
    path: /tmp/telegraf-rpm.key
    state: absent
  changed_when: false

- name: Add InfluxData Telegraf YUM repository
  ansible.builtin.yum_repository:
    name: influxdata-telegraf
    description: "InfluxData Telegraf Repository"
    baseurl: "{{ telegraf_rpm_repo_baseurl }}"
    gpgcheck: yes
    gpgkey: "{{ telegraf_key_url }}"
    enabled: yes

- name: Install Telegraf package
  ansible.builtin.yum:
    name: "{{ item }}"
    state: latest
  loop:
    - "{{ telegraf_package }}"
